### ISSUE TITLE
Gulp build error

### ISSUE THREAD

**Issue by hassan-bazzi** [deepditch/deep.web#27]
```$ gulp build
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../project.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/hassanbazzi/deep.ditch/deep.web/gulp-tasks/build-css.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Did you forget to commit this project.config file? I can't find it anywhere @drakesvoboda

Frontend seems to work fine without it though

**Comment by hassan-bazzi** [comment]
jk
